Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -13,15 +13,19 @@ jobs:
       - name: Install Dependencies
         run: pip install -r mlops/requirements.txt
 
-      - name: Debug script content
+      - name: Debug: show script content
         run: cat mlops/model_building/data_register.py
 
-      - name: List directories
+      - name: Debug: list directories
         run: |
+          echo "Current path:"
           pwd
+          echo "Root directory:"
           ls -l
-          ls -l mlops
-          ls -l mlops/data || echo "❗ mlops/data not found"
+          echo "Inside 'mlops' directory:"
+          ls -l mlops || echo "mlops not found"
+          echo "Inside 'mlops/data' directory:"
+          ls -l mlops/data || echo "mlops/data not found"
 
       - name: Upload Dataset to Hugging Face Hub
         env:
