Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -9,8 +9,20 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+
       - name: Install Dependencies
         run: pip install -r mlops/requirements.txt
+
+      - name: 🔍 Debug script content
+        run: cat mlops/model_building/data_register.py
+
+      - name: 📂 List directories
+        run: |
+          pwd
+          ls -l
+          ls -l mlops
+          ls -l mlops/data || echo "❗ mlops/data not found"
+
       - name: Upload Dataset to Hugging Face Hub
         env:
           HF_TOKEN: ${{ secrets.HF_TOKEN }}
@@ -28,7 +40,6 @@ jobs:
           HF_TOKEN: ${{ secrets.HF_TOKEN }}
         run: python mlops/model_building/prep.py
 
-
   model-traning:
     needs: data-prep
     runs-on: ubuntu-latest
@@ -41,10 +52,9 @@ jobs:
           HF_TOKEN: ${{ secrets.HF_TOKEN }}
         run: python mlops/model_building/train.py
 
-
   deploy-hosting:
     runs-on: ubuntu-latest
-    needs: [model-traning,data-prep,register-dataset]
+    needs: [model-traning, data-prep, register-dataset]
     steps:
       - uses: actions/checkout@v3
       - name: Install Dependencies
